// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TariffAPI.Models;

namespace TariffAPI.Migrations
{
    [DbContext(typeof(TariffContext))]
    [Migration("20181205044009_TarifFMigr")]
    partial class TarifFMigr
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TariffAPI.Models.InvoiceMaster", b =>
                {
                    b.Property<int>("invoiceId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("invoiceName")
                        .IsRequired();

                    b.Property<byte>("isActive");

                    b.HasKey("invoiceId");

                    b.ToTable("InvoiceMaster");
                });

            modelBuilder.Entity("TariffAPI.Models.ParameterMaster", b =>
                {
                    b.Property<int>("parameterId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte>("isActive");

                    b.Property<string>("parameterName")
                        .IsRequired();

                    b.HasKey("parameterId");

                    b.ToTable("ParameterMaster");
                });

            modelBuilder.Entity("TariffAPI.Models.RuleDetails", b =>
                {
                    b.Property<int>("ruleId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("invoiceId");

                    b.Property<byte>("isActive");

                    b.Property<int>("parameterId");

                    b.Property<string>("ruleValue")
                        .IsRequired();

                    b.HasKey("ruleId");

                    b.HasIndex("invoiceId");

                    b.ToTable("RuleDetails");
                });

            modelBuilder.Entity("TariffAPI.Models.RuleDetails", b =>
                {
                    b.HasOne("TariffAPI.Models.InvoiceMaster", "invoiceMaster")
                        .WithMany("ruleDetails")
                        .HasForeignKey("invoiceId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
